        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 31 15:16:18 2018
        MODULE PERM_UNIFORM__genmod
          INTERFACE 
            SUBROUTINE PERM_UNIFORM(N,SEED,P)
              INTEGER(KIND=4) :: N
              INTEGER(KIND=4) :: SEED
              INTEGER(KIND=4) :: P(N)
            END SUBROUTINE PERM_UNIFORM
          END INTERFACE 
        END MODULE PERM_UNIFORM__genmod
