        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 31 15:16:17 2018
        MODULE R8MAT_UNIFORM_01__genmod
          INTERFACE 
            SUBROUTINE R8MAT_UNIFORM_01(M,N,SEED,R)
              INTEGER(KIND=4) :: N
              INTEGER(KIND=4) :: M
              INTEGER(KIND=4) :: SEED
              REAL(KIND=8) :: R(M,N)
            END SUBROUTINE R8MAT_UNIFORM_01
          END INTERFACE 
        END MODULE R8MAT_UNIFORM_01__genmod
