        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 31 15:16:18 2018
        MODULE TIMESTAMP__genmod
          INTERFACE 
            SUBROUTINE TIMESTAMP
            END SUBROUTINE TIMESTAMP
          END INTERFACE 
        END MODULE TIMESTAMP__genmod
